#!/usr/bin/env python3
"""
gui_train_model.py
----------------------------------
A student-friendly GUI to train a YOLOv11 detection model on labeled datasets.

REQUIREMENTS (install once):
  pip install customtkinter ultralytics matplotlib pillow

EXPECTED DATA FORMAT (per selected dataset):
  class_name/
    images/  -> image files (.jpg/.png/...)
    labels/  -> YOLO .txt files (class_id x_center y_center width height) normalized

RUN:
  python gui_train_model.py
"""

import os
import csv
import time
import shutil
import random
import threading
from pathlib import Path
from glob import glob

# GUI
import customtkinter as ctk
from tkinter import filedialog, messagebox

# Charts
import matplotlib
matplotlib.use("Agg")  # render off-screen; we'll load images into the GUI
import matplotlib.pyplot as plt
from PIL import Image, ImageTk

# ML
from ultralytics import YOLO


# =========================
# Constants / Theme
# =========================
IMG_SIZE = 640  # fixed
LR_CHOICES = ["0.1", "0.05", "0.01", "0.005", "0.001"]

THEME_BLUE = "#0F3D91"
THEME_BLUE_LIGHT = "#2456C0"
THEME_ACCENT_RED = "#E53935"
THEME_ACCENT_RED_HOVER = "#C62828"
CARD_BG = "#FFFFFF"
MUTE = "#666666"
BORDER_OFF = "#E6E9F5"
BORDER_ON = THEME_BLUE

# Global font family preference (falls back if not installed)
FONT_FAMILY = "Roboto"


# =========================
# Dataset helpers
# =========================
def list_images(folder: Path):
    return [p for p in folder.glob("*.*") if p.suffix.lower() in [".jpg", ".jpeg", ".png", ".bmp", ".webp"]]

def copy_and_remap_class(
    class_root: Path,
    dst_images_dir: Path,
    dst_labels_dir: Path,
    new_class_id: int,
    keep_ratio: float,
    seed: int = 42,
):
    """
    Copy images/labels from a single CLASS folder into dst_* and REMAP labels' class IDs to new_class_id.
    Structure expected:
      class_name/
        images/
        labels/
    Returns: (train_count, val_count)
    """
    images_src = class_root / "images"
    labels_src = class_root / "labels"
    if not images_src.exists() or not labels_src.exists():
        raise ValueError(f"Missing images/labels in: {class_root}")

    images = list_images(images_src)
    pairs = []
    for img in images:
        lbl = labels_src / f"{img.stem}.txt"
        if lbl.exists():
            pairs.append((img, lbl))

    random.seed(seed)
    random.shuffle(pairs)
    k = int(len(pairs) * keep_ratio)
    train_pairs = pairs[:k]
    val_pairs = pairs[k:]

    # Ensure dirs
    (dst_images_dir / "train").mkdir(parents=True, exist_ok=True)
    (dst_images_dir / "val").mkdir(parents=True, exist_ok=True)
    (dst_labels_dir / "train").mkdir(parents=True, exist_ok=True)
    (dst_labels_dir / "val").mkdir(parents=True, exist_ok=True)

    def _copy_pair(img_path: Path, lbl_path: Path, out_img_dir: Path, out_lbl_dir: Path):
        # copy image
        dst_img = out_img_dir / img_path.name
        shutil.copy2(img_path, dst_img)
        # rewrite label
        dst_lbl = out_lbl_dir / lbl_path.name
        with open(lbl_path, "r") as fin, open(dst_lbl, "w") as fout:
            for line in fin:
                parts = line.strip().split()
                if len(parts) >= 5:
                    parts[0] = str(new_class_id)
                    fout.write(" ".join(parts) + "\n")

    for img, lbl in train_pairs:
        _copy_pair(img, lbl, dst_images_dir / "train", dst_labels_dir / "train")

    for img, lbl in val_pairs:
        _copy_pair(img, lbl, dst_images_dir / "val", dst_labels_dir / "val")

    return len(train_pairs), len(val_pairs)

def build_data_yaml(workdir: Path, class_names: list):
    """
    Create a data.yaml for YOLOv11 detection with absolute paths.
    """
    workdir = workdir.expanduser().resolve()
    data_yaml = workdir / "data.yaml"
    train_dir = (workdir / "images" / "train").as_posix()
    val_dir   = (workdir / "images" / "val").as_posix()

    content = f"""# Auto-generated by orbit_odyssey_yolov11_detect_gui.py
# Using absolute paths so Ultralytics doesn't redirect to its datasets folder
train: {train_dir}
val: {val_dir}

names:
"""
    for idx, name in enumerate(class_names):
        content += f"  {idx}: {name}\n"

    with open(data_yaml, "w") as f:
        f.write(content)
    return data_yaml


# =========================
# Metrics plotting
# =========================
def plot_detection_metrics(run_dir: Path):
    """
    From results.csv create:
      - pr.png: Precision & Recall vs epoch
      - loss.png: Validation loss curves
    Returns (pr_path, loss_path) or (None, None).
    """
    results_csv = run_dir / "results.csv"
    if not results_csv.exists():
        return None, None

    epochs, precision, recall = [], [], []
    val_box, val_cls, val_dfl = [], [], []

    def _get_float(row, keys, default=0.0):
        for k in keys:
            if k in row and row[k] != "":
                try:
                    return float(row[k])
                except:
                    pass
        # fuzzy match
        for rk, rv in row.items():
            for key in keys:
                if key in rk and rv not in ("", None):
                    try:
                        return float(rv)
                    except:
                        continue
        return default

    with open(results_csv, "r", newline="") as f:
        reader = csv.DictReader(f)
        e = 0
        for row in reader:
            try:
                e = int(row.get("epoch", e))
            except:
                pass
            epochs.append(e)
            precision.append(_get_float(row, ["metrics/precision", "metrics/precision(B)"], 0.0))
            recall.append(_get_float(row, ["metrics/recall", "metrics/recall(B)"], 0.0))
            val_box.append(_get_float(row, ["val/box_loss"], 0.0))
            val_cls.append(_get_float(row, ["val/cls_loss"], 0.0))
            val_dfl.append(_get_float(row, ["val/dfl_loss"], 0.0))

    # PR
    plt.figure()
    plt.plot(epochs, precision, label="Precision")
    plt.plot(epochs, recall, label="Recall")
    plt.xlabel("Epoch")
    plt.ylabel("Score")
    plt.title("Precision & Recall vs Epoch")
    plt.grid(True, alpha=0.3)
    plt.legend()
    pr_path = run_dir / "pr.png"
    plt.savefig(pr_path, bbox_inches="tight")
    plt.close()

    # Loss
    tot = [a + b + c for a, b, c in zip(val_box, val_cls, val_dfl)]
    plt.figure()
    plt.plot(epochs, tot, label="val/total_loss")
    if any(val_box):
        plt.plot(epochs, val_box, label="val/box_loss")
    if any(val_cls):
        plt.plot(epochs, val_cls, label="val/cls_loss")
    if any(val_dfl):
        plt.plot(epochs, val_dfl, label="val/dfl_loss")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.title("Validation Loss vs Epoch")
    plt.grid(True, alpha=0.3)
    plt.legend()
    loss_path = run_dir / "loss.png"
    plt.savefig(loss_path, bbox_inches="tight")
    plt.close()

    return pr_path, loss_path


# =========================
# GUI Components
# =========================
def RFont(size=14, weight="normal"):
    """Create a Roboto font (fallback built-in if not installed)."""
    return ctk.CTkFont(family=FONT_FAMILY, size=size, weight=weight)

class Card(ctk.CTkFrame):
    """Rounded card container with border (toggleable)."""
    def __init__(self, master, border_on=False, **kwargs):
        super().__init__(master, corner_radius=18, fg_color=CARD_BG,
                         border_width=2, border_color=(BORDER_ON if border_on else BORDER_OFF), **kwargs)
        self.grid_columnconfigure(0, weight=1)
        self.grid_rowconfigure(99, weight=1)

    def set_border(self, on: bool):
        self.configure(border_color=(BORDER_ON if on else BORDER_OFF))


class DatasetTile(ctk.CTkFrame):
    """
    A big clickable tile for selecting a single CLASS folder.
    - Title: "Dataset 1/2/3"
    - Click tile to open folder chooser
    - Shows chosen path (trimmed) under the title
    - "Use Dataset" button toggles inclusion and border highlight
    """
    def __init__(self, master, title: str, on_toggle=None):
        super().__init__(master, corner_radius=16, fg_color=CARD_BG, border_width=2, border_color=BORDER_OFF)
        self.grid_columnconfigure(0, weight=1)

        self.on_toggle = on_toggle
        self.used = ctk.BooleanVar(value=False)
        self.path = ctk.StringVar(value="")
        self.title = title

        # Big clickable area
        self.tile_btn = ctk.CTkButton(
            self, text=title, height=80, width=280,
            font=RFont(20, "bold"),
            fg_color="#F5F8FF", text_color=THEME_BLUE,
            hover_color="#ECF2FF",
            command=self._browse
        )
        self.tile_btn.grid(row=0, column=0, padx=12, pady=(12, 6), sticky="ew")

        # Selected path (small label)
        self.path_lbl = ctk.CTkLabel(self, text="No folder selected", text_color=MUTE, font=RFont(12))
        self.path_lbl.grid(row=1, column=0, padx=14, pady=(0, 10), sticky="w")

        # Use toggle
        self.use_btn = ctk.CTkButton(
            self, text="Use Dataset", height=36, width=140,
            font=RFont(14, "bold"),
            command=self._toggle_use
        )
        self.use_btn.grid(row=2, column=0, padx=12, pady=(0, 12))

    def _browse(self):
        path = filedialog.askdirectory(title=f"Select CLASS Folder ({self.title})")
        if path:
            self.path.set(path)
            # Show tidy path (folder name & parent)
            p = Path(path)
            display = f"{p.name}  (…/{p.parent.name}/{p.name})"
            self.path_lbl.configure(text=display)
            # Auto-turn ON use if previously off (optional; keep off to require explicit click)
            # self._set_used(True)

    def _toggle_use(self):
        # Only allow ON if path selected
        if not self.path.get():
            messagebox.showwarning("No folder selected", f"Select a folder for {self.title} before enabling it.")
            return
        self._set_used(not self.used.get())

    def _set_used(self, state: bool):
        self.used.set(state)
        # Outline tile when ON
        self.configure(border_color=(BORDER_ON if state else BORDER_OFF))
        self.tile_btn.configure(text_color=(THEME_BLUE if state else THEME_BLUE))
        # Notify parent
        if self.on_toggle:
            self.on_toggle(self, state)


# =========================
# Main App
# =========================
class App(ctk.CTk):
    def __init__(self):
        super().__init__()
        ctk.set_appearance_mode("light")
        ctk.set_default_color_theme("blue")

        self.title("🚀 Orbit Odyssey — YOLOv11 Trainer")
        self.geometry("1220x860")
        self.minsize(1140, 820)

        # Root grid
        self.grid_columnconfigure(0, weight=1)
        self.grid_rowconfigure(3, weight=1)

        # ===== Header =====
        header = Card(self)
        header.grid(row=0, column=0, padx=18, pady=(18, 10), sticky="nsew")
        header.grid_columnconfigure(0, weight=1)

        title = ctk.CTkLabel(
            header,
            text="Orbit Odyssey — AI + XRP Detection Trainer 🛰️",
            font=RFont(30, "bold"),
            text_color=THEME_BLUE,
        )
        subtitle = ctk.CTkLabel(
            header,
            text="Select datasets • Auto-build YAML • Train YOLOv11 • View precision/recall & loss charts",
            font=RFont(16, "bold"),
            text_color=THEME_BLUE_LIGHT,
        )
        title.grid(row=0, column=0, padx=24, pady=(18, 6), sticky="w")
        subtitle.grid(row=1, column=0, padx=24, pady=(0, 18), sticky="w")

        # ===== Top row: Datasets + Parameters =====
        top_row = ctk.CTkFrame(self, fg_color="transparent")
        top_row.grid(row=1, column=0, padx=18, pady=8, sticky="nsew")
        top_row.grid_columnconfigure(0, weight=1)
        top_row.grid_columnconfigure(1, weight=1)

        # -- Datasets card
        ds_card = Card(top_row)
        ds_card.grid(row=0, column=0, padx=(0, 9), pady=0, sticky="nsew")
        ctk.CTkLabel(ds_card, text="🗂️  Select Class Folders", font=RFont(20, "bold"), text_color=THEME_BLUE)\
            .grid(row=0, column=0, padx=18, pady=(18, 10), sticky="w")

        tiles_row = ctk.CTkFrame(ds_card, fg_color="transparent")
        tiles_row.grid(row=1, column=0, padx=12, pady=(4, 18), sticky="nsew")
        tiles_row.grid_columnconfigure((0, 1, 2), weight=1)

        # Three dataset tiles
        self.tile1 = DatasetTile(tiles_row, "Dataset 1", on_toggle=self._tile_toggled)
        self.tile2 = DatasetTile(tiles_row, "Dataset 2", on_toggle=self._tile_toggled)
        self.tile3 = DatasetTile(tiles_row, "Dataset 3", on_toggle=self._tile_toggled)
        self.tile1.grid(row=0, column=0, padx=8, pady=8, sticky="nsew")
        self.tile2.grid(row=0, column=1, padx=8, pady=8, sticky="nsew")
        self.tile3.grid(row=0, column=2, padx=8, pady=8, sticky="nsew")

        hint = ctk.CTkLabel(
            ds_card,
            text="Each selected folder must be a CLASS folder with images/ and labels/ inside.\n"
                 "The trainer remaps class IDs to 0..k-1 and auto-generates data.yaml.",
            font=RFont(12),
            text_color=MUTE,
        )
        hint.grid(row=2, column=0, padx=18, pady=(0, 16), sticky="w")

        # -- Parameters card
        param_card = Card(top_row)
        param_card.grid(row=0, column=1, padx=(9, 0), pady=0, sticky="nsew")
        ctk.CTkLabel(param_card, text="⚙️  Training Parameters", font=RFont(20, "bold"), text_color=THEME_BLUE)\
            .grid(row=0, column=0, padx=18, pady=(18, 10), sticky="w")

        # Train split
        self.split_var = ctk.DoubleVar(value=0.8)
        self._row_slider(param_card, 1, "Train split", self.split_var, 0.5, 0.95, step=0.01, fmt="{:.2f}")

        # Learning rate presets
        lr_row = ctk.CTkFrame(param_card, fg_color="transparent")
        lr_row.grid(row=2, column=0, padx=18, pady=10, sticky="ew")
        lr_row.grid_columnconfigure(1, weight=1)
        ctk.CTkLabel(lr_row, text="Learning rate (α)", font=RFont(14)).grid(row=0, column=0, padx=(0, 12), sticky="w")
        self.lr_var = ctk.DoubleVar(value=0.01)
        lr_menu = ctk.CTkOptionMenu(lr_row, values=LR_CHOICES, command=lambda v: self.lr_var.set(float(v)), width=160,
                                     font=RFont(14))
        lr_menu.set("0.01")
        lr_menu.grid(row=0, column=1, sticky="w")

        # Model size
        ms_row = ctk.CTkFrame(param_card, fg_color="transparent")
        ms_row.grid(row=3, column=0, padx=18, pady=10, sticky="ew")
        ms_row.grid_columnconfigure(1, weight=1)
        ctk.CTkLabel(ms_row, text="Model size (YOLOv11)", font=RFont(14)).grid(row=0, column=0, padx=(0, 12), sticky="w")
        self.model_size_var = ctk.StringVar(value="n")
        ctk.CTkOptionMenu(ms_row, values=["n", "s", "m", "l", "x"], variable=self.model_size_var, width=160,
                          font=RFont(14)).grid(row=0, column=1, sticky="w")

        # Epochs
        self.epochs_var = ctk.IntVar(value=20)
        self._row_slider(param_card, 4, "Epochs", self.epochs_var, 5, 100, step=1, fmt="{:d}")

        # Working dir
        wd_row = ctk.CTkFrame(param_card, fg_color="transparent")
        wd_row.grid(row=5, column=0, padx=18, pady=(10, 18), sticky="ew")
        wd_row.grid_columnconfigure(1, weight=1)
        ctk.CTkLabel(wd_row, text="Working dir", font=RFont(14)).grid(row=0, column=0, padx=(0, 12), sticky="w")
        self.workdir_var = ctk.StringVar(value="student_detect_run")
        ctk.CTkEntry(wd_row, textvariable=self.workdir_var, placeholder_text="Folder to build merged dataset…",
                     font=RFont(14)).grid(row=0, column=1, sticky="ew")

        # ===== Train & Progress =====
        train_card = Card(self)
        train_card.grid(row=2, column=0, padx=18, pady=8, sticky="nsew")
        train_card.grid_columnconfigure(0, weight=1)
        ctk.CTkLabel(train_card, text="🎯 Train & Progress", font=RFont(20, "bold"), text_color=THEME_BLUE)\
            .grid(row=0, column=0, padx=18, pady=(18, 10), sticky="w")

        btn_row = ctk.CTkFrame(train_card, fg_color="transparent")
        btn_row.grid(row=1, column=0, padx=18, pady=(0, 8), sticky="ew")
        btn_row.grid_columnconfigure(2, weight=1)

        self.train_btn = ctk.CTkButton(btn_row, text="Train YOLOv11", width=200, height=46, font=RFont(16, "bold"),
                                       command=self.start_training_thread)
        self.train_btn.grid(row=0, column=0, padx=(0, 12))

        self.reset_btn = ctk.CTkButton(btn_row, text="Reset", width=140, height=46, font=RFont(15, "bold"),
                                       fg_color=THEME_ACCENT_RED, hover_color=THEME_ACCENT_RED_HOVER,
                                       command=self._reset_workdir)
        self.reset_btn.grid(row=0, column=1, padx=(0, 12))

        self.progress = ctk.CTkProgressBar(train_card, height=12)
        self.progress.grid(row=2, column=0, padx=18, pady=(4, 18), sticky="ew")
        self.progress.set(0)

        # ===== Output & Metrics =====
        bottom = ctk.CTkFrame(self, fg_color="transparent")
        bottom.grid(row=3, column=0, padx=18, pady=(0, 18), sticky="nsew")
        bottom.grid_columnconfigure(0, weight=1)
        bottom.grid_columnconfigure(1, weight=1)
        bottom.grid_rowconfigure(0, weight=1)

        # Output
        output_card = Card(bottom)
        output_card.grid(row=0, column=0, padx=(0, 9), sticky="nsew")
        ctk.CTkLabel(output_card, text="📜 Output", font=RFont(20, "bold"), text_color=THEME_BLUE)\
            .grid(row=0, column=0, padx=18, pady=(18, 8), sticky="w")
        self.out = ctk.CTkTextbox(output_card, height=260, font=RFont(13))
        self.out.grid(row=1, column=0, padx=18, pady=(0, 18), sticky="nsew")

        # Metrics
        metrics_card = Card(bottom)
        metrics_card.grid(row=0, column=1, padx=(9, 0), sticky="nsew")
        metrics_card.grid_columnconfigure(0, weight=1)
        ctk.CTkLabel(metrics_card, text="📈 Metrics", font=RFont(20, "bold"), text_color=THEME_BLUE)\
            .grid(row=0, column=0, padx=18, pady=(18, 8), sticky="w")

        self.pr_img_label = ctk.CTkLabel(metrics_card, text="Precision/Recall chart will appear here after training.",
                                         text_color=MUTE, font=RFont(12))
        self.loss_img_label = ctk.CTkLabel(metrics_card, text="Loss chart will appear here after training.",
                                           text_color=MUTE, font=RFont(12))
        self.pr_img_label.grid(row=1, column=0, padx=18, pady=(4, 10), sticky="nsew")
        self.loss_img_label.grid(row=2, column=0, padx=18, pady=(0, 18), sticky="nsew")

        self._log("Welcome! Click each Dataset box to select a CLASS folder, then toggle “Use Dataset” to include it.")

    # ---------- UI helpers ----------
    def _row_slider(self, parent, row_idx, label, var, vmin, vmax, step=1, fmt="{:d}"):
        row = ctk.CTkFrame(parent, fg_color="transparent")
        row.grid(row=row_idx, column=0, padx=18, pady=10, sticky="ew")
        row.grid_columnconfigure(1, weight=1)

        ctk.CTkLabel(row, text=label, font=RFont(14)).grid(row=0, column=0, padx=(0, 12), sticky="w")
        slider = ctk.CTkSlider(
            row, from_=vmin, to=vmax, number_of_steps=int((vmax - vmin) / step) if step else 0,
            command=lambda v: val_lbl.configure(text=fmt.format(var.set(type(var.get())(float(v))) or var.get()))
        )
        slider.set(var.get())
        slider.grid(row=0, column=1, padx=(0, 10), sticky="ew")
        val_lbl = ctk.CTkLabel(row, text=fmt.format(var.get()), width=70,
                               fg_color="#E3ECFF", corner_radius=10, font=RFont(13, "bold"))
        val_lbl.grid(row=0, column=2, sticky="e")

    def _tile_toggled(self, tile: DatasetTile, state: bool):
        # Could add additional logic if needed when a tile is toggled
        pass

    def _reset_workdir(self):
        workdir = Path(self.workdir_var.get())
        if workdir.exists():
            try:
                shutil.rmtree(workdir)
                self._log(f"[•] Reset: removed working dir {workdir}")
            except Exception as e:
                messagebox.showerror("Reset error", str(e))
        else:
            self._log("[•] Nothing to reset.")

    def _log(self, msg: str):
        self.out.insert("end", msg + "\n")
        self.out.see("end")

    def start_training_thread(self):
        self.train_btn.configure(state="disabled")
        self.progress.set(0)
        threading.Thread(target=self._train_model_safe, daemon=True).start()

    def _train_model_safe(self):
        try:
            self._train_model()
        except Exception as e:
            messagebox.showerror("Training error", str(e))
            self._log(f"[!] Error: {e}")
        finally:
            self.train_btn.configure(state="normal")
            self.progress.set(0)

    # ---------- Training ----------
    def _train_model(self):
        # Gather selected datasets (tiles)
        selected_paths = []
        class_names = []
        for tile in (self.tile1, self.tile2, self.tile3):
            if tile.used.get():
                p = tile.path.get().strip()
                if not p:
                    raise ValueError(f"{tile.title} is enabled but no folder is selected.")
                if not Path(p).exists():
                    raise ValueError(f"Selected folder does not exist for {tile.title}: {p}")
                selected_paths.append(p)
                class_names.append(Path(p).name)

        if not selected_paths:
            raise ValueError("Please enable at least one Dataset by selecting a folder and clicking 'Use Dataset'.")

        split = float(self.split_var.get())
        lr = float(self.lr_var.get())
        model_size = self.model_size_var.get().strip()
        epochs = int(self.epochs_var.get())
        workdir = Path(self.workdir_var.get()).expanduser().resolve()

        # Prepare workdir
        if workdir.exists():
            shutil.rmtree(workdir)
        images_dir = workdir / "images"
        labels_dir = workdir / "labels"
        (images_dir / "train").mkdir(parents=True, exist_ok=True)
        (images_dir / "val").mkdir(parents=True, exist_ok=True)
        (labels_dir / "train").mkdir(parents=True, exist_ok=True)
        (labels_dir / "val").mkdir(parents=True, exist_ok=True)

        self._log(f"[i] Merging classes: {', '.join(class_names)}")
        self.progress.set(0.12)

        # Merge + remap
        for new_id, class_path in enumerate(selected_paths):
            tr, va = copy_and_remap_class(
                class_root=Path(class_path),
                dst_images_dir=images_dir,
                dst_labels_dir=labels_dir,
                new_class_id=new_id,
                keep_ratio=split,
                seed=42
            )
            self._log(f"[+] {Path(class_path).name} → ID {new_id} | train: {tr}, val: {va}")

        # Build YAML
        data_yaml = build_data_yaml(workdir, class_names)
        self._log(f"[i] Generated {data_yaml}")
        self.progress.set(0.25)

        # Train YOLOv11 detection
        weights = f"yolo11{model_size}.pt"
        self._log(f"[i] Training: weights={weights}, lr={lr}, epochs={epochs}, imgsz={IMG_SIZE}")
        self.progress.set(0.3)
        model = YOLO(weights)

        t0 = time.perf_counter()
        model.train(
            data=str(data_yaml),
            epochs=epochs,
            imgsz=IMG_SIZE,
            lr0=lr,
            project="runs/detect",
            name=None,
            verbose=True,
            device = "cpu",
            workers=0,          # IMPORTANT on Windows to avoid CUDA worker crashes
            amp=True,           # mixed precision; saves VRAM
            cache=False,        # avoid caching in RAM/GPU
            mosaic=0, mixup=0, copy_paste=0,
        )
        elapsed = time.perf_counter() - t0
        self._log(f"[✓] Training completed in {elapsed:.2f} seconds.")
        self.progress.set(0.8)

        # Find run dir & plots
        run_dir = self._find_latest_run_dir("detect")
        if not run_dir:
            self._log("[!] Could not locate the run directory.")
            return

        best_weights = run_dir / "weights" / "best.pt"
        last_weights = run_dir / "weights" / "last.pt"
        if best_weights.exists():
            self._log(f"[+] Best model: {best_weights}")
        if last_weights.exists():
            self._log(f"[+] Last model: {last_weights}")

        export_src = best_weights if best_weights.exists() else last_weights
        if export_src.exists():
            export_model = YOLO(str(export_src))
            onnx_path = export_model.export(format="onnx", half=True)
            self._log(f"[+] ONNX exported: {onnx_path}")


        pr_path, loss_path = plot_detection_metrics(run_dir)
        self.progress.set(0.9)
        if pr_path and loss_path:
            self._show_chart(pr_path, self.pr_img_label, max_height=280)
            self._show_chart(loss_path, self.loss_img_label, max_height=280)
            self._log(f"[+] Charts saved:\n    {pr_path}\n    {loss_path}")

        # Summary
        self._log("\n=== SUMMARY ===")
        self._log(f"Classes: {', '.join(class_names)} (nc={len(class_names)})")
        self._log(f"Train split: {split:.2f} | LR: {lr} | Model: yolo11{model_size}.pt | Epochs: {epochs}")
        self._log(f"Image size: {IMG_SIZE} (fixed)")
        self._log(f"Training time (s): {elapsed:.2f}")
        self._log(f"Run folder: {run_dir}")
        self.progress.set(1.0)

    def _find_latest_run_dir(self, task_subdir: str):
        candidates = sorted(glob(f"runs/{task_subdir}/*"), key=os.path.getmtime)
        return Path(candidates[-1]) if candidates else None

    def _show_chart(self, img_path: Path, target_label: ctk.CTkLabel, max_height=280):
        """Load a chart image and display it nicely."""
        img = Image.open(img_path).convert("RGB")
        w, h = img.size
        scale = min(1.0, max_height / h)
        new_w, new_h = int(w * scale), int(h * scale)
        img = img.resize((new_w, new_h), Image.LANCZOS)
        tkimg = ImageTk.PhotoImage(img)
        target_label.configure(image=tkimg, text="")
        target_label.image = tkimg  # keep reference


def main():
    app = App()
    app.mainloop()


if __name__ == "__main__":
    main()